site_name: API-Go2Doc
# site_url: https://example.com/
repo_url: https://github.com/rickey-alok/mk-doc
repo_name: rickey-alok/mk-doc
theme:
  name: material
  language: en
  logo: https://t4.ftcdn.net/jpg/03/22/95/69/360_F_322956978_9ESBVewTYdhSu9G6qf2JazX9tUsdh53g.jpg
  favicon: https://t4.ftcdn.net/jpg/03/22/95/69/360_F_322956978_9ESBVewTYdhSu9G6qf2JazX9tUsdh53g.jpg
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    admonition:
      type: material/alert-box
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - toc.integerate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotations
    - content.code.copy
    - content.action.view
    - content.action.edit
  palette:
    # - primary: custom
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

use_directory_urls: true
nav:
  - Home: home.md
  - Docs-as-Code:
      - API: Docs-as-Code/API.md
      - Git & GitHub: Docs-as-Code/Git-GitHub.md
      - VS-Code: Docs-as-Code/VS-Code.md

extra_css:
  - stylesheets/extra.css

# extra:
#   # alternate:
#   #   - name: English
#   #     link: /en/
#   #     lang: en
#   #   - name: Deutsch
#   #     link: /de/
#   #     lang: de
#   analytics:
#     feedback:
#       title: Was this page helpful?
#       ratings:
#         - icon: material/emoticon-happy-outline
#           name: This page was helpful
#           data: 1
#           note: >-
#             Thanks for your feedback!
#         - icon: material/emoticon-sad-outline
#           name: This page could be improved
#           data: 0
#           note: >-
#             Thanks for your feedback! Help us improve this page by
#             using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
# plugins:
#   - git-authors

copyright: Copyright &copy; 2024 , Maintained by the <a href="https://www.linkedin.com/in/alok-ranjan-34817a17/">Alok Ranjan</a>.

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
