site_name: VertoFX
site_url: https://example.com/
repo_url: https://github.com/rickey-alok/mk-doc
repo_name: rickey-alok/mk-doc
theme:
  name: material
  logo: https://play-lh.googleusercontent.com/UYrUUWxFLGzHn5qD1R-n75ReIWG_Vy3xXGo7crY0_WnAA419A6KEROV6cjyP6qV0Wbw=w240-h480-rw
  favicon: https://play-lh.googleusercontent.com/UYrUUWxFLGzHn5qD1R-n75ReIWG_Vy3xXGo7crY0_WnAA419A6KEROV6cjyP6qV0Wbw=w240-h480-rw
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - toc.integerate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotations
    - content.code.copy
    - content.action.view
    - content.action.edit
  language: en
  palette:
    # - primary: custom
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

use_directory_urls: true
nav:
  - API - Technical Integration Guide:
      - Introduction: API - Technical Integration Guide/Introduction.md
      - Quick Start Guide: API - Technical Integration Guide/Quick Start Guide.md
  - VertoFX APIs:
      - Login: VertoFX APIs/Login.md
      - Get FX Rate: VertoFX APIs/Get FX Rate.md
      - Create FX Rate: VertoFX APIs/Create FX Rate.md

extra_css:
  - stylesheets/extra.css

# exclude_docs: |
#   *.py

# markdown_extensions:
#   - toc:
#       permalink: 
#   - attr_list
#   - def_list
#   - tables
#   - pymdownx.highlight:
#       use_pygments: false
#   - pymdownx.snippets
#   - pymdownx.superfences
#   - callouts
#   - mdx_gh_links:
#       user: mkdocs
#       repo: mkdocs
#   - mkdocs-click
copyright: Copyright &copy; 2024 , Maintained by the <a href="https://www.linkedin.com/in/alok-ranjan-34817a17/">Alok Ranjan</a>.
# hooks:
#   - docs/hooks.py

# plugins:
#   - search
#   - redirects:
#       redirect_maps:
#         user-guide/plugins.md: dev-guide/plugins.md
#         user-guide/custom-themes.md: dev-guide/themes.md
#         user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md
#   - autorefs
#   - literate-nav:
#       nav_file: README.md
#       implicit_index: true
#   - mkdocstrings:
#       handlers:
#         python:
#           options:
#             docstring_section_style: list
#             members_order: source
#             show_root_heading: true
#             show_source: false
#             show_signature_annotations: true

# watch:
#   - mkdocs

extra:
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
plugins:
  - git-authors
